
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Main", targetNamespace = "http://ws.middleRM/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Main {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "abort", targetNamespace = "http://ws.middleRM/", className = "client.Abort")
    @ResponseWrapper(localName = "abortResponse", targetNamespace = "http://ws.middleRM/", className = "client.AbortResponse")
    @Action(input = "http://ws.middleRM/Main/abortRequest", output = "http://ws.middleRM/Main/abortResponse")
    public boolean abort(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "shutdown", targetNamespace = "http://ws.middleRM/", className = "client.Shutdown")
    @ResponseWrapper(localName = "shutdownResponse", targetNamespace = "http://ws.middleRM/", className = "client.ShutdownResponse")
    @Action(input = "http://ws.middleRM/Main/shutdownRequest", output = "http://ws.middleRM/Main/shutdownResponse")
    public boolean shutdown();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "start", targetNamespace = "http://ws.middleRM/", className = "client.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://ws.middleRM/", className = "client.StartResponse")
    @Action(input = "http://ws.middleRM/Main/startRequest", output = "http://ws.middleRM/Main/startResponse")
    public int start();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://ws.middleRM/", className = "client.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://ws.middleRM/", className = "client.CommitResponse")
    @Action(input = "http://ws.middleRM/Main/commitRequest", output = "http://ws.middleRM/Main/commitResponse")
    public boolean commit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFlight", targetNamespace = "http://ws.middleRM/", className = "client.AddFlight")
    @ResponseWrapper(localName = "addFlightResponse", targetNamespace = "http://ws.middleRM/", className = "client.AddFlightResponse")
    @Action(input = "http://ws.middleRM/Main/addFlightRequest", output = "http://ws.middleRM/Main/addFlightResponse")
    public boolean addFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteFlight", targetNamespace = "http://ws.middleRM/", className = "client.DeleteFlight")
    @ResponseWrapper(localName = "deleteFlightResponse", targetNamespace = "http://ws.middleRM/", className = "client.DeleteFlightResponse")
    @Action(input = "http://ws.middleRM/Main/deleteFlightRequest", output = "http://ws.middleRM/Main/deleteFlightResponse")
    public boolean deleteFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryFlight", targetNamespace = "http://ws.middleRM/", className = "client.QueryFlight")
    @ResponseWrapper(localName = "queryFlightResponse", targetNamespace = "http://ws.middleRM/", className = "client.QueryFlightResponse")
    @Action(input = "http://ws.middleRM/Main/queryFlightRequest", output = "http://ws.middleRM/Main/queryFlightResponse")
    public int queryFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryFlightPrice", targetNamespace = "http://ws.middleRM/", className = "client.QueryFlightPrice")
    @ResponseWrapper(localName = "queryFlightPriceResponse", targetNamespace = "http://ws.middleRM/", className = "client.QueryFlightPriceResponse")
    @Action(input = "http://ws.middleRM/Main/queryFlightPriceRequest", output = "http://ws.middleRM/Main/queryFlightPriceResponse")
    public int queryFlightPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCars", targetNamespace = "http://ws.middleRM/", className = "client.AddCars")
    @ResponseWrapper(localName = "addCarsResponse", targetNamespace = "http://ws.middleRM/", className = "client.AddCarsResponse")
    @Action(input = "http://ws.middleRM/Main/addCarsRequest", output = "http://ws.middleRM/Main/addCarsResponse")
    public boolean addCars(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCars", targetNamespace = "http://ws.middleRM/", className = "client.DeleteCars")
    @ResponseWrapper(localName = "deleteCarsResponse", targetNamespace = "http://ws.middleRM/", className = "client.DeleteCarsResponse")
    @Action(input = "http://ws.middleRM/Main/deleteCarsRequest", output = "http://ws.middleRM/Main/deleteCarsResponse")
    public boolean deleteCars(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCars", targetNamespace = "http://ws.middleRM/", className = "client.QueryCars")
    @ResponseWrapper(localName = "queryCarsResponse", targetNamespace = "http://ws.middleRM/", className = "client.QueryCarsResponse")
    @Action(input = "http://ws.middleRM/Main/queryCarsRequest", output = "http://ws.middleRM/Main/queryCarsResponse")
    public int queryCars(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCarsPrice", targetNamespace = "http://ws.middleRM/", className = "client.QueryCarsPrice")
    @ResponseWrapper(localName = "queryCarsPriceResponse", targetNamespace = "http://ws.middleRM/", className = "client.QueryCarsPriceResponse")
    @Action(input = "http://ws.middleRM/Main/queryCarsPriceRequest", output = "http://ws.middleRM/Main/queryCarsPriceResponse")
    public int queryCarsPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRooms", targetNamespace = "http://ws.middleRM/", className = "client.AddRooms")
    @ResponseWrapper(localName = "addRoomsResponse", targetNamespace = "http://ws.middleRM/", className = "client.AddRoomsResponse")
    @Action(input = "http://ws.middleRM/Main/addRoomsRequest", output = "http://ws.middleRM/Main/addRoomsResponse")
    public boolean addRooms(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteRooms", targetNamespace = "http://ws.middleRM/", className = "client.DeleteRooms")
    @ResponseWrapper(localName = "deleteRoomsResponse", targetNamespace = "http://ws.middleRM/", className = "client.DeleteRoomsResponse")
    @Action(input = "http://ws.middleRM/Main/deleteRoomsRequest", output = "http://ws.middleRM/Main/deleteRoomsResponse")
    public boolean deleteRooms(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryRooms", targetNamespace = "http://ws.middleRM/", className = "client.QueryRooms")
    @ResponseWrapper(localName = "queryRoomsResponse", targetNamespace = "http://ws.middleRM/", className = "client.QueryRoomsResponse")
    @Action(input = "http://ws.middleRM/Main/queryRoomsRequest", output = "http://ws.middleRM/Main/queryRoomsResponse")
    public int queryRooms(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryRoomsPrice", targetNamespace = "http://ws.middleRM/", className = "client.QueryRoomsPrice")
    @ResponseWrapper(localName = "queryRoomsPriceResponse", targetNamespace = "http://ws.middleRM/", className = "client.QueryRoomsPriceResponse")
    @Action(input = "http://ws.middleRM/Main/queryRoomsPriceRequest", output = "http://ws.middleRM/Main/queryRoomsPriceResponse")
    public int queryRoomsPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newCustomer", targetNamespace = "http://ws.middleRM/", className = "client.NewCustomer")
    @ResponseWrapper(localName = "newCustomerResponse", targetNamespace = "http://ws.middleRM/", className = "client.NewCustomerResponse")
    @Action(input = "http://ws.middleRM/Main/newCustomerRequest", output = "http://ws.middleRM/Main/newCustomerResponse")
    public int newCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newCustomerId", targetNamespace = "http://ws.middleRM/", className = "client.NewCustomerId")
    @ResponseWrapper(localName = "newCustomerIdResponse", targetNamespace = "http://ws.middleRM/", className = "client.NewCustomerIdResponse")
    @Action(input = "http://ws.middleRM/Main/newCustomerIdRequest", output = "http://ws.middleRM/Main/newCustomerIdResponse")
    public boolean newCustomerId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCustomer", targetNamespace = "http://ws.middleRM/", className = "client.DeleteCustomer")
    @ResponseWrapper(localName = "deleteCustomerResponse", targetNamespace = "http://ws.middleRM/", className = "client.DeleteCustomerResponse")
    @Action(input = "http://ws.middleRM/Main/deleteCustomerRequest", output = "http://ws.middleRM/Main/deleteCustomerResponse")
    public boolean deleteCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveFlight", targetNamespace = "http://ws.middleRM/", className = "client.ReserveFlight")
    @ResponseWrapper(localName = "reserveFlightResponse", targetNamespace = "http://ws.middleRM/", className = "client.ReserveFlightResponse")
    @Action(input = "http://ws.middleRM/Main/reserveFlightRequest", output = "http://ws.middleRM/Main/reserveFlightResponse")
    public boolean reserveFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveCar", targetNamespace = "http://ws.middleRM/", className = "client.ReserveCar")
    @ResponseWrapper(localName = "reserveCarResponse", targetNamespace = "http://ws.middleRM/", className = "client.ReserveCarResponse")
    @Action(input = "http://ws.middleRM/Main/reserveCarRequest", output = "http://ws.middleRM/Main/reserveCarResponse")
    public boolean reserveCar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveRoom", targetNamespace = "http://ws.middleRM/", className = "client.ReserveRoom")
    @ResponseWrapper(localName = "reserveRoomResponse", targetNamespace = "http://ws.middleRM/", className = "client.ReserveRoomResponse")
    @Action(input = "http://ws.middleRM/Main/reserveRoomRequest", output = "http://ws.middleRM/Main/reserveRoomResponse")
    public boolean reserveRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveItinerary", targetNamespace = "http://ws.middleRM/", className = "client.ReserveItinerary")
    @ResponseWrapper(localName = "reserveItineraryResponse", targetNamespace = "http://ws.middleRM/", className = "client.ReserveItineraryResponse")
    @Action(input = "http://ws.middleRM/Main/reserveItineraryRequest", output = "http://ws.middleRM/Main/reserveItineraryResponse")
    public boolean reserveItinerary(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Object> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCustomerInfo", targetNamespace = "http://ws.middleRM/", className = "client.QueryCustomerInfo")
    @ResponseWrapper(localName = "queryCustomerInfoResponse", targetNamespace = "http://ws.middleRM/", className = "client.QueryCustomerInfoResponse")
    @Action(input = "http://ws.middleRM/Main/queryCustomerInfoRequest", output = "http://ws.middleRM/Main/queryCustomerInfoResponse")
    public String queryCustomerInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
